### ISSUE TITLE
홈화면 위젯 크기 관련 issue

### ISSUE THREAD

**Issue by game240** [IceCream0910/kw-klas-plus#2]
![Screenshot_20240911_112742_One UI Home](https://github.com/user-attachments/assets/3eaebc9a-49d6-413e-8627-bf579a3b911e)
첨부된 사진과 같이 2×2 사이즈인 위젯 상하로 투명한 영역이 함께 포함되어 3×2 사이즈처럼 됩니다.

(S23U, one ui 6.1, 안드로이드 14)

**Comment by IceCream0910** [comment]
이슈 제보 감사합니다.
### 재현 조건
One UI 홈 설정에서 홈화면 배열을 기본 설정인 4x6이 아닌 다른 배열로 설정(첨부하신 사진은 5x5 배열 적용 상태) 되었을 때 상하단 여백이 발생하는 것으로 보입니다.
 
### 해결 필요성
해당 이슈에 대해 분석하던 중 타사 앱들(네이버, 카카오톡)의 2x2 정사각형 위젯의 경우에도 홈화면 배열에 따라 동일 이슈가 발생하는 것을 확인하였습니다. 위젯의 정사각형 비율을 유지해야 하기 때문에 레이아웃에 따라 상하단 여백 공간이 발생하는 것은 불가피해 보입니다. 다만, 다른 위젯이나 아이콘들과 함께 배치할 때 사용자 경험을 저해할 수 있어 개선할 필요가 있다고 판단됩니다.

### 해결
[feat: allow widget resize](https://github.com/IceCream0910/kw-klas-plus/commit/f96fbd525574712f35c7baab479d6b96b5981c28) 를 통해 위젯을 길게 눌러 가로/세로 크기를 사용자가 직접 드래그하여 조절할 수 있도록 허용하였습니다.
![Screenshot_20240913_012545_One UI Home](https://github.com/user-attachments/assets/a0f8e4e0-a018-48ca-adff-7d20ccf43b1c)
만약, 위젯 비율 이슈와 관련해 더 좋은 해결 방안이 있다면 남겨주시기 바랍니다. 추가 의견이 없다면 다음 업데이트에 `위젯 크기 조절 허용`이 반영될 예정입니다.
