### ISSUE TITLE
QR코드 자동 갱신 구현

### ISSUE THREAD

**Issue by mirusu400** [IceCream0910/kw-klas-plus#3]
광운대 출입시 QR코드 인증은 Expire Time이 대략 1분정도로 정해져있습니다

현재 KLAS+같은 경우에는 QR코드 인증 시작을하면 1회만 QR코드 인증을 받아와서 1분이 넘어가면 재시도해야하는 문제가있습니다

결론적으로 1분(혹은 약 50초 정도)에서 재 갱신을 한번더 하는 기능을 추가하면 좋을것같습니다~

**Comment by IceCream0910** [comment]
다음 사진과 같이 모바일 학생증 modal 내에서 QR 코드를 갱신할 수 있는 버튼과 함께 50초 간격으로 자동 갱신되는 기능을 추가하였습니다.
추후 배포될 업데이트 버전에서 반영될 예정입니다.
좋은 의견 감사합니다!
[feat: 모바일 학생증 QR 자동 갱신](https://github.com/IceCream0910/kw-klas-plus/commit/f928c5292f3fcb9711a91fc41ade797c650c2403)
![Screenshot_20241006_031135_KLAS+](https://github.com/user-attachments/assets/8b100911-f288-43f7-8593-ea0b712a9daa)
