### ISSUE TITLE
사용자의 User Agent를 가져오게 수정

### ISSUE THREAD

**Issue by mirusu400** [IceCream0910/kw-klas-plus#4]
https://github.com/IceCream0910/kw-klas-plus/blob/4ec0c33abe5698aa051f700007706354d38587e2/app/src/main/java/com/icecream/kwklasplus/QRScanActivity.kt#L101

해당 코드 등 일부 코드를 보면 웹 요청 전송시 하드코딩된 `User Agent`를 이용해 보내고 있습니다

이렇게 하게되면 KLAS+를 사용하는 유저를 특정할 수 있게되서 (학교가 보안에 신경쓰지 않는것같지만) 추후 어뷰징 등으로 생각할 수 있어 보입니다

제가 Android SDK에 대해선 잘 모르지만, Webview나 Chrome의 User Agent를 가져오거나 휴대폰 정보를 Replace하면 좋을것같습니다

**Comment by IceCream0910** [comment]
[update: fetch 헤더 user-agent 하드 코딩 제거](https://github.com/IceCream0910/kw-klas-plus/commit/d0cfd2cd10f90c7e53fe9d5530625a842741efe1)

웹 요청 시 User Agent를 하드코딩이 아닌 실제 유저 디바이스의 UA값으로 요청을 전송하도록 수정했습니다.
```kotlin
val defaultUserAgent = WebSettings.getDefaultUserAgent(this)
val requestBuilder =
    Request.Builder()
        .header("User-Agent", "$defaultUserAgent NuriwareApp")
```
